# Generated by Django 3.2 on 2024-06-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Password',
            field=models.CharField(default='test@123', max_length=500),
        ),
    ]
